name: Lint double link
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    name: readme lint find double links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Scrum/awesome-readme-lint-double-link-action@v0.1.13
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
